---
# this is the cloudfoundry manifest for the dev system
applications:
- name: metadatamanagement
  path: ../target/metadatamanagement-test.war
  memory: 1024M
  disk_quota: 1024M
  instances: 3
  host: metadatamanagement-test
  buildpack: https://github.com/cloudfoundry/java-buildpack
  env:
    SPRING_PROFILES_ACTIVE: test
    JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{ enabled: false }'
  services:
  - mongodb
  - elasticsearch
  - email
  - dara
  - rabbitmq
  timeout: 180
  health-check-type: http
  health-check-http-endpoint: /management/info
