---
# this is the cloudfoundry manifest for the prod system
applications:
- name: metadatamanagement
  path: ../target/metadatamanagement-prod.war
  memory: 1024M
  disk_quota: 1024M
  instances: 3
  host: metadatamanagement
  buildpack: https://github.com/cloudfoundry/java-buildpack
  env:
    SPRING_PROFILES_ACTIVE: prod
    JAVA_OPTS: -Duser.timezone=Europe/Berlin
    JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{ enabled: false }'
  services:
  - mongodb
  - elasticsearch
  - email
  timeout: 180
