---
# this is the cloudfoundry manifest for the prod system
applications:
- name: metadatamanagement
  path: ../target/metadatamanagement-prod.war
  memory: 1024M
  disk_quota: 1024M
  instances: 3
  buildpack: https://github.com/cloudfoundry/java-buildpack
  env:
    SPRING_PROFILES_ACTIVE: prod
    JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{ enabled: false }'
  services:
  - mongodb
  - elasticsearch
  - email
  - dara
  timeout: 180
  health-check-type: http
  health-check-http-endpoint: /management/info
  routes:
  - route: metadata.fdz.dzhw.eu
  - route: metadatamanagement.cfapps.io
